### PR TITLE
#13 Enhance Fizzbuzz

### PR DESCRIPTION
**Pull request by tommygithub**
Created Services directory and created fizzbuzzservice.cs. Made a new pull request to match issue number. I also probably should have said something other than "Enhance Fizzbuzz" in the commit, since it's basically the exact title of the issue. Or is that okay?

### CODE REVIEW

**Comment by jayhilden** [comment]
The commit comment should be about what you changed mostly.  I would have said something like "#13 moved fizzbuzz to a service, renamed accordingly".

Since you created a pull request for #13 does that mean that all of the items in that issue are complete?  What did you decide on for a model?

**Comment by tommygithub** [comment]
Alright. Should I usually only pull request when I think the issue is done? To answer your question "What are you trying to display on the screen?" I'm displaying the FizzBuzz results. Which is what the index.cshtml is doing, so I'm thinking that code should be in the model?

**Comment by jayhilden** [comment]
A pull request says "hey, I'm done, please review and merge into master".  If you just want someone to review code you can always commit the code, push it to github, and then you have the option to comment on either individual lines of a commit or a commit as a whole.

You said "I'm displaying the FizzBuzz results".  I'm trying to get you to think about what those results are.  Are they a linked list?  Are they a guid?  What kind of data are you going to be displaying?

**Comment by tommygithub** [comment]
Closing pull request. Will do request once issue is completed.

**Pull request closed without merging**
