### PR TITLE
#5 fizz buzz

### PR DESCRIPTION
**Pull request by tommygithub**
Created FizzBuzz service, but still figuring out the view model.

### CODE REVIEW

**Comment by jayhilden** [comment]
@tommygithub when thinking about the view model answer this question: "what are you trying ti display on the screen?"

**Comment by jayhilden** [comment]
@tommygithub I'm also curious, why did you prefix your commit comment with the number 5?

**Comment by tommygithub** [comment]
Yeah I should have named it "Fizz-buzz service".

**Comment by jayhilden** [comment]
I think this is the 3rd time I've mentioned this: I suggest that you prefix your commit comments with **the issue number that you are working on**

So if you're working on this issue:
image


Then I would expect the commit comment prefixed with #13, because you are working on issue #13.  That's how github links things together.  Notice that when you hover over #13 in this comment it shows what I'm referring to.

Calling your branch "issue/13" would also have helped to make it more clear which issue you are working on.

Does that make sense?

**Comment by tommygithub** [comment]
Yep makes sense.

**Pull request closed without merging**
